---
title: "Figure_3_data_analysis"
output: html_document
date: "2024-01-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

```{r}
library('Seurat')
library('ggplot2')
library('plyr')
library('dplyr')
```

```{r}
#Step 1: Input data and remove high- and low-count nuclei

IC_1d_1.data <- Read10X(data.dir = "1_SourceFiles/IC_1d_1/")
IC_1d_1 <- CreateSeuratObject(counts = IC_1d_1.data, project = "IC_1d_1", 
                              min.cells = 3, min.features = 1000)
IC_1d_1

VlnPlot(IC_1d_1, features = c("nFeature_RNA"))
IC_1d_1 <- subset(IC_1d_1, subset = nFeature_RNA > 1000 & nFeature_RNA < 8000)
IC_1d_1


IC_1d_1 <- NormalizeData(IC_1d_1, normalization.method = "LogNormalize", scale.factor = 10000)

IC_1d_1 <- FindVariableFeatures(IC_1d_1, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_1d_1)

IC_1d_1 <- ScaleData(IC_1d_1, features = all.genes)

IC_1d_1 <- RunPCA(IC_1d_1, features = VariableFeatures(object = IC_1d_1), npcs = 100)

IC_1d_1 <- FindNeighbors(IC_1d_1, dims = 1:30)

IC_1d_1 <- FindClusters(IC_1d_1, resolution = 0.5)

IC_1d_1 <- RunUMAP(IC_1d_1, dims = 1:30)

DimPlot(IC_1d_1, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500


#Remove the clearly stressed, dying, or artificially low cell count clusters, then recluster

VlnPlot(IC_1d_1, "nFeature_RNA", pt.size = 0) + NoLegend() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5)) +
  theme(text = element_text(size = 20)) #1500 x 500

```


```{r}
DotPlot(IC_1d_1, features = c("Mef2c", "Camk2a", "Ptk2b", "Satb2", 
                              "Crym", "Fezf2", "Bcl6", "Slc30a3", "Sulf1",
                              "Bcl11b","Cux2","Dcc","Unc5d","BC0F70"),
        dot.scale = 4, dot.min = 0) + coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5),
        axis.text = element_text(size = 10)) #Sized for display

#Cluster 7 is removed

IC_1d_1 <- subset(IC_1d_1, idents = c("7"), invert = TRUE)

#Recluster

IC_1d_1 <- NormalizeData(IC_1d_1, normalization.method = "LogNormalize", scale.factor = 10000)

IC_1d_1 <- FindVariableFeatures(IC_1d_1, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_1d_1)

IC_1d_1 <- ScaleData(IC_1d_1, features = all.genes)

IC_1d_1 <- RunPCA(IC_1d_1, features = VariableFeatures(object = IC_1d_1), npcs = 100)

IC_1d_1 <- FindNeighbors(IC_1d_1, dims = 1:30)

IC_1d_1 <- FindClusters(IC_1d_1, resolution = 0.5)

IC_1d_1 <- RunUMAP(IC_1d_1, dims = 1:30)

DimPlot(IC_1d_1, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

#Detect Barcode sequences

#create an average expression file, mostly to verifiy the exact barcode names
# but also to get a sense of barcode distribution across seurat clusters.

DefaultAssay(IC_1d_1) <- "RNA"
```

```{r}
avgexp_IC_1d_1 <- AverageExpression(IC_1d_1, assay = 'RNA', 
                                    features = rownames(IC_1d_1@assays$RNA$counts),
                                    group.by = c('seurat_clusters'))


write.csv(x = avgexp_IC_1d_1, 
          file = "avgexp_IC_1d_1.csv",
          quote = FALSE)


#Examination of the file indicates "BC0" is abundant in 0,1,4
#Step 2: 

#There is a command that returns the PERCENT of total reads that come from an given gene. 

PercentageFeatureSet(IC_1d_1,pattern="BC0") -> IC_1d_1$percent.BC0


write.csv(x = IC_1d_1@meta.data,
          file = "IC_1d_1_MD.csv",
          quote = FALSE)


#In excel, 1) add a column named "injury.status" that indicates "Uninjured" or "IC_1d_1" according to barcode
#and 2)place "CellID" as the column header for the cell identifications
#Save the result in 2_Input_Files with an "_back" added (save as .csv of course)

#The following commands read the csv file back into R, indicate the column that containst the 
#cell identifier, and the inputs the data from the uploaded file into metadata.

IC_1d_1_injury.status <- read.csv("2_Input_Lists/IC_1d_1_MD_back.csv",
                                  sep = ",")

rownames(IC_1d_1_injury.status) <- IC_1d_1_injury.status$CellID

IC_1d_1 <- AddMetaData(object = IC_1d_1, metadata = IC_1d_1_injury.status)

#Check that it all worked:
Idents (IC_1d_1) <- "injury.status"
levels (IC_1d_1)

#If desired, create gene list of DEGs between Injured and Not_Injured (the final version
#of DEGs will derive later from the unified file)

IC_1d_1_Inj_vs_not <- FindMarkers(IC_1d_1,
                                  ident.1 = c("IC_1d"),
                                  ident.2 = c("Uninjured"),
                                  logfc.threshold = 0.32,
                                  min.pct = 0.05)


write.csv(x = IC_1d_1_Inj_vs_not,
          file = "IC_1d_1_Inj_vs_not.csv",
          quote = FALSE)


#If desired, visualize candidate DEGs (again, final versions will be from the unified file)

FeaturePlot(IC_1d_1, c("Creb5"), label = FALSE, pt.size = 1, split.by = "injury.status",
            label.size = 5, repel = TRUE, order = TRUE, min.cutoff = 0,
            max.cutoff = 6, cols = c("lightgrey", "red")) +
  theme(text = element_text(size = 25),
        axis.text = element_text(size = 40)) +
  NoLegend() + NoAxes() #300 x 3000


VlnPlot(IC_1d_1, "Creb5", pt.size = .1) + NoLegend() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5)) +
  theme(text = element_text(size = 20)) #1500 x 500
```

```{r}
#Input 28_IC3_3d_all data

IC_3d_all.data <- Read10X(data.dir = "1_SourceFiles/IC_3d_1/")
IC_3d_all <- CreateSeuratObject(counts = IC_3d_all.data, project = "IC_3d_all", 
                                min.cells = 3, min.features = 1000)
IC_3d_all

VlnPlot(IC_3d_all, features = c("nFeature_RNA"))
IC_3d_all <- subset(IC_3d_all, subset = nFeature_RNA > 1000 & nFeature_RNA < 8000)
IC_3d_all

IC_3d_all <- NormalizeData(IC_3d_all, normalization.method = "LogNormalize", scale.factor = 10000)

IC_3d_all <- FindVariableFeatures(IC_3d_all, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_3d_all)

IC_3d_all <- ScaleData(IC_3d_all, features = all.genes)

IC_3d_all <- RunPCA(IC_3d_all, features = VariableFeatures(object = IC_3d_all), npcs = 100)

IC_3d_all <- FindNeighbors(IC_3d_all, dims = 1:30)

IC_3d_all <- FindClusters(IC_3d_all, resolution = 0.5)

IC_3d_all <- RunUMAP(IC_3d_all, dims = 1:30)

DimPlot(IC_3d_all, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

#Remove any artificially low cell count clusters, then recluster

VlnPlot(IC_3d_all, "nFeature_RNA", pt.size = 0) + NoLegend() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5)) +
  theme(text = element_text(size = 20)) #1500 x 500

#8 and 11 are removed
IC_3d_all <- subset(IC_3d_all, idents = c("8","11"), invert = TRUE)

#recluster

IC_3d_all <- NormalizeData(IC_3d_all, normalization.method = "LogNormalize", scale.factor = 10000)

IC_3d_all <- FindVariableFeatures(IC_3d_all, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_3d_all)

IC_3d_all <- ScaleData(IC_3d_all, features = all.genes)

IC_3d_all <- RunPCA(IC_3d_all, features = VariableFeatures(object = IC_3d_all), npcs = 100)

IC_3d_all <- FindNeighbors(IC_3d_all, dims = 1:30)

IC_3d_all <- FindClusters(IC_3d_all, resolution = 0.5)

IC_3d_all <- RunUMAP(IC_3d_all, dims = 1:30)

DimPlot(IC_3d_all, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

```

```{r}
### Identify CST and also establish markers to exclude non-CST cortical cells and determine their number

DotPlot(IC_3d_all, features = c("Mef2c", "Camk2a", "Ptk2b", "Satb2", 
                                "Crym", "Fezf2", "Bcl6", "Slc30a3", "Sulf1",
                                "Cux2","Unc5d","Vwc2l","Dcc"),
        dot.scale = 4, dot.min = 0) + coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5),
        axis.text = element_text(size = 10)) #Sized for display

#7 is removed

IC_3d_all <- subset(IC_3d_all, idents = c(7), invert = TRUE)

#Recluster

IC_3d_all <- NormalizeData(IC_3d_all, normalization.method = "LogNormalize", scale.factor = 10000)

IC_3d_all <- FindVariableFeatures(IC_3d_all, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_3d_all)

IC_3d_all <- ScaleData(IC_3d_all, features = all.genes)

IC_3d_all <- RunPCA(IC_3d_all, features = VariableFeatures(object = IC_3d_all), npcs = 100)

IC_3d_all <- FindNeighbors(IC_3d_all, dims = 1:10)

IC_3d_all <- FindClusters(IC_3d_all, resolution = 0.5)

IC_3d_all <- RunUMAP(IC_3d_all, dims = 1:10)

Idents(IC_3d_all) <- "seurat_clusters"

DimPlot(IC_3d_all, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

#create an average expression file, mostly to verify the exact barcode names
# but also to get a sense of barcode distribution across seurat clusters.

DefaultAssay(IC_3d_all) <- "RNA"

avgexp_IC_3d_all <- AverageExpression(IC_3d_all, assay = 'RNA', 
                                      features = rownames(IC_3d_all@assays$RNA$counts),
                                      group.by = c('seurat_clusters'))


write.csv(x = avgexp_IC_3d_all, 
          file = "avgexp_IC_3d_all.csv",
          quote = FALSE)


#Find PERCENT of total reads that come from each barcode. 

PercentageFeatureSet(IC_3d_all,pattern="80BC0") -> IC_3d_all$percent.BC0
PercentageFeatureSet(IC_3d_all,pattern="80BC1") -> IC_3d_all$percent.BC1
PercentageFeatureSet(IC_3d_all,pattern="80BC6") -> IC_3d_all$percent.BC6
PercentageFeatureSet(IC_3d_all,pattern="80BC7") -> IC_3d_all$percent.BC7


###Assign injury status to the dataset
write.csv(x = IC_3d_all@meta.data,
          file = "IC_3d_all_MD.csv",
          quote = FALSE)

IC_3d_all_injury.status <- read.csv("2_Input_Lists/IC_3d_all_MD_back.csv",
                                    sep = ",")
rownames(IC_3d_all_injury.status) <- IC_3d_all_injury.status$CellID

IC_3d_all <- AddMetaData(object = IC_3d_all, metadata = IC_3d_all_injury.status)

#Check that it all worked:
Idents (IC_3d_all) <- "injury.status"
levels (IC_3d_all)

Idents (IC_3d_all) <- "Classification"
levels (IC_3d_all)

#Extact control-treated cells from the overall datasets
IC_3d_1 <- subset(IC_3d_all, idents = c("BC0_1"), invert = FALSE)

Idents (IC_3d_1) <- "Classification"
levels(IC_3d_1)

FeaturePlot(IC_3d_1, c("Rhoq"), label = FALSE, pt.size = 2,
            label.size = 5, repel = TRUE, order = TRUE, min.cutoff = 0,
            max.cutoff = 6, cols = c("lightgrey", "red")) +
  theme(text = element_text(size = 25),
        axis.text = element_text(size = 40)) +
  NoLegend() + NoAxes() #300 x 3000


#Recluster the final set and check for non-CST cell types

IC_3d_1 <- NormalizeData(IC_3d_1, normalization.method = "LogNormalize", scale.factor = 10000)

IC_3d_1 <- FindVariableFeatures(IC_3d_1, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_3d_1)

IC_3d_1 <- ScaleData(IC_3d_1, features = all.genes)

IC_3d_1 <- RunPCA(IC_3d_1, features = VariableFeatures(object = IC_3d_1), npcs = 100)

IC_3d_1 <- FindNeighbors(IC_3d_1, dims = 1:30)

IC_3d_1 <- FindClusters(IC_3d_1, resolution = 0.5)

IC_3d_1 <- RunUMAP(IC_3d_1, dims = 1:30)

DimPlot(IC_3d_1, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

DotPlot(IC_3d_1, features = c("Mef2c", "Camk2a", "Ptk2b", "Satb2", 
                              "Crym", "Fezf2", "Bcl6", "Slc30a3", "Sulf1",
                              "Cux2","Unc5d","Vwc2l","Dcc"),
        dot.scale = 4, dot.min = 0) + coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5),
        axis.text = element_text(size = 10)) #Sized for display
```


```{r}
FeaturePlot(IC_3d_1, c("Creb5"), label = FALSE, pt.size = 1, split.by = "injury.status",
            label.size = 5, repel = TRUE, order = TRUE, min.cutoff = 0,
            max.cutoff = 6, cols = c("lightgrey", "red")) +
  theme(text = element_text(size = 25),
        axis.text = element_text(size = 40)) +
  NoLegend() + NoAxes()
```

```{r}
#7 day intracortical data. Uninjured and injured nuclei were pre-labeled with molecular barcodes and mixed prior to library construction. Barcodes are used here to de-multiplex

IC_7d_1.data <- Read10X(data.dir = "1_SourceFiles/IC_7d_1/")
IC_7d_1 <- CreateSeuratObject(counts = IC_7d_1.data, project = "IC_7d_1", 
                              min.cells = 3, min.features = 1000)
IC_7d_1

VlnPlot(IC_7d_1, features = c("nFeature_RNA"))
IC_7d_1 <- subset(IC_7d_1, subset = nFeature_RNA > 1000 & nFeature_RNA < 8000)
IC_7d_1

#Cluster

IC_7d_1 <- NormalizeData(IC_7d_1, normalization.method = "LogNormalize", scale.factor = 10000)

IC_7d_1 <- FindVariableFeatures(IC_7d_1, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_7d_1)

IC_7d_1 <- ScaleData(IC_7d_1, features = all.genes)

IC_7d_1 <- RunPCA(IC_7d_1, features = VariableFeatures(object = IC_7d_1), npcs = 100)

IC_7d_1 <- FindNeighbors(IC_7d_1, dims = 1:30)

IC_7d_1 <- FindClusters(IC_7d_1, resolution = 0.5)

IC_7d_1 <- RunUMAP(IC_7d_1, dims = 1:30)

DimPlot(IC_7d_1, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

#Remove any clearly stressed, dying, or artificially low cell count clusters, then recluster

VlnPlot(IC_7d_1, "nFeature_RNA", pt.size = 0) + NoLegend() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5)) +
  theme(text = element_text(size = 20)) #1500 x 500


#None are removed
```

```{r}
### Identify CST and also establish markers to exclude non- CST cortical cells and determine their number

# A dotplot with the mentioned  markers

DotPlot(IC_7d_1, features = c("Mef2c", "Camk2a", "Ptk2b", "Satb2", 
                              "Crym", "Fezf2", "Bcl6", "Slc30a3", "Sulf1",
                              "Bcl11b","Cux2","Unc5d"),
        dot.scale = 4, dot.min = 0) + coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5),
        axis.text = element_text(size = 10)) #Sized for display

#Clusters 5 and 6 appear to be shallow layer

IC_7d_1 <- subset(IC_7d_1, idents = c("5","6"), invert = TRUE)

#Recluster

IC_7d_1 <- NormalizeData(IC_7d_1, normalization.method = "LogNormalize", scale.factor = 10000)

IC_7d_1 <- FindVariableFeatures(IC_7d_1, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_7d_1)

IC_7d_1 <- ScaleData(IC_7d_1, features = all.genes)

IC_7d_1 <- RunPCA(IC_7d_1, features = VariableFeatures(object = IC_7d_1), npcs = 100)

IC_7d_1 <- FindNeighbors(IC_7d_1, dims = 1:30)

IC_7d_1 <- FindClusters(IC_7d_1, resolution = 0.5)

IC_7d_1 <- RunUMAP(IC_7d_1, dims = 1:30)

DimPlot(IC_7d_1, reduction = "umap", label = TRUE, pt.size = 1, label.size = 10
) + NoLegend() +
  theme(axis.text = element_text(size = 20),
        text = element_text (size = 20)) #2880 x 1500

#Detect Barcode sequences

#Step 1: create an average expression file, mostly to verifiy the exact barcode names
# but also to get a sense of barcode distribution across seurat clusters.

PercentageFeatureSet(IC_7d_1,pattern="BC0F70") -> IC_7d_1$percent.BC0
PercentageFeatureSet(IC_7d_1,pattern="BC1F70") -> IC_7d_1$percent.BC1


write.csv(x = IC_7d_1@meta.data,
          file = "IC_7d_1_MD.csv",
          quote = FALSE)

```

```{r}

IC_7d_1_injury.status <- read.csv("2_Input_Lists/IC_7d_1_MD_back.csv",
                                  sep = ",")

rownames(IC_7d_1_injury.status) <- IC_7d_1_injury.status$CellID

IC_7d_1 <- AddMetaData(object = IC_7d_1, metadata = IC_7d_1_injury.status)

#Check that it all worked:
Idents (IC_7d_1) <- "injury.status"
levels (IC_7d_1)

FeaturePlot(IC_7d_1, c("Creb5"), label = FALSE, pt.size = 1,split.by = "injury.status",
            label.size = 5, repel = TRUE, order = TRUE, min.cutoff = 0,
            max.cutoff = 6, cols = c("lightgrey", "red")) +
  theme(text = element_text(size = 25),
        axis.text = element_text(size = 40)) +
  NoLegend() + NoAxes() #300 x 3000


IC_7d_1_Inj_vs_not <- FindMarkers(IC_7d_1,
                                  ident.1 = c("IC_7d"),
                                  ident.2 = c("Uninjured"),
                                  logfc.threshold = 0,
                                  min.pct = 0.01)


write.csv(x = IC_7d_1_Inj_vs_not,
          file = "IC_7d_1_Inj_vs_not_S5.csv",
          quote = FALSE)


```
# Merge ALL Data sets
```{r}
IC_merge.list <- list (IC_1d_1,IC_7d_1, IC_3d_1)

IC_merge.list <- lapply(X=IC_merge.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = IC_merge.list)

IC_merge.anchors <- FindIntegrationAnchors(object.list = IC_merge.list,
                                           anchor.features = features)

IC_merge <- IntegrateData(anchorset = IC_merge.anchors)

DefaultAssay(IC_merge) <- "integrated"

IC_merge <- ScaleData(IC_merge, verbose = FALSE)

IC_merge <- RunPCA(IC_merge, npcs = 50, verbose = FALSE)

IC_merge <- RunUMAP(IC_merge, reduction = "pca", dims = 1:30)

IC_merge <- FindNeighbors(IC_merge, reduction = "pca", dims = 1:30)

IC_merge <- FindClusters(IC_merge, resolution = 0.5)

DefaultAssay(IC_merge) <- "RNA"

IC_merge

# Some visualizations for initial assessment of clustering and sample bias

DimPlot(IC_merge, group.by = 'seurat_clusters', split.by = 'orig.ident',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

DimPlot(IC_merge, group.by = 'seurat_clusters', split.by = 'injury.status',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500


# Remove the clearly stressed, dying, or artificially low cell count clusters, then recluster

VlnPlot(IC_merge, "nFeature_RNA", pt.size = 0) + NoLegend() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5)) +
  theme(text = element_text(size = 20)) #1500 x 500


```
```{r}
DimPlot(IC_merge, group.by = 'orig.ident',label = TRUE, label.size = 5) + NoLegend() # 1500 x 500
DimPlot(IC_merge, group.by = 'injury.status',label = TRUE, label.size = 5) + NoLegend() # 1500 x 500
```


```{r}
#Cluster 4 has markedly lower feature counts and is removed
IC_merge <- subset(x = IC_merge, idents = c("5"), invert = TRUE)

#Recluster

DefaultAssay(IC_merge) <- "RNA"

IC_merge <- NormalizeData(IC_merge, normalization.method = "LogNormalize", scale.factor = 10000)

IC_merge <- FindVariableFeatures(IC_merge, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(IC_merge)

IC_merge <- ScaleData(IC_merge, features = all.genes)

IC_merge <- RunPCA(IC_merge, features = VariableFeatures(object = IC_merge), npcs = 50)

IC_merge <- FindNeighbors(IC_merge, dims = 1:30)
IC_merge <- FindClusters(IC_merge, resolution = 0.5)

IC_merge <- RunUMAP(IC_merge, dims = 1:30)

DimPlot(IC_merge, group.by = 'seurat_clusters', split.by = 'orig.ident',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

DimPlot(IC_merge, group.by = 'seurat_clusters',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

DimPlot(IC_merge, group.by = 'injury.status',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

#re-confirm CST identity

DotPlot(IC_merge, features = c("Mef2c", "Camk2a", "Ptk2b", "Satb2", 
                               "Crym", "Fezf2", "Bcl6", "Slc30a3", "Sulf1",
                               "Cux2","Unc5d","Vwc2l","Dcc"),
        dot.scale = 4, dot.min = 0) + coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = .5),
        axis.text = element_text(size = 10)) #Sized for display

#All clusters appear to be CST

IC_merge 


DimPlot(IC_merge, group.by = 'injury.status',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

FeaturePlot(IC_merge, c("Atf3"), label = TRUE, split.by = "orig.ident",
            label.size = 5, repel = TRUE, order = TRUE) #500 x 500


FeaturePlot(IC_merge, c("Sprr1a"), label = FALSE,pt.size = 1,
            label.size = 5, repel = TRUE, order = TRUE) #500 x 500

FeaturePlot(IC_merge, c("Ecel1"), label = TRUE, split.by = "injury.status",
            label.size = 5, repel = TRUE, order = TRUE) #500 x 500

FeaturePlot(IC_merge, c("nFeature_RNA"), label = TRUE, 
            label.size = 5, repel = TRUE, order = TRUE) #500 x 500

Idents(IC_merge) <- "injury.status"

DimPlot(IC_merge, group.by = 'seurat_clusters', split.by = 'orig.ident',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

DimPlot(IC_merge, group.by = 'injury.status',
        label = TRUE, label.size = 5) + NoLegend() # 1500 x 500

```


```{r}
Idents(IC_merge) <- 'seurat_clusters'
levels(IC_merge)
IC_merge <- JoinLayers(IC_merge)
```

```{r}
Idents(IC_merge) <- 'seurat_clusters'
IC_merge_0v1 <- FindMarkers(IC_merge,
                            ident.1 = c("0"),
                            ident.2 = c("1"),
                            logfc.threshold = 0,
                            min.pct = 0.01)

write.csv(x = IC_merge_0v1,
          file = "IC_merge_0v1.csv",
          quote = FALSE)

Idents(IC_merge) <- "injury.status"
levels(IC_merge)



IC_merge_IC_1d <- FindMarkers(IC_merge,
                              ident.1 = c("IC_1d"),
                              ident.2 = c("Uninjured"),
                              logfc.threshold = 0,
                              min.pct = 0.001)

write.csv(x = IC_merge_IC_1d,
          file = "IC_merge_IC_1d.csv",
          quote = FALSE)

IC_merge_IC_3d <- FindMarkers(IC_merge,
                              ident.1 = c("IC_3d"),
                              ident.2 = c("Uninjured"),
                              logfc.threshold = 0,
                              min.pct = 0.001)

write.csv(x = IC_merge_IC_3d,
          file = "IC_merge_IC_3d.csv",
          quote = FALSE)

IC_merge_IC_7d <- FindMarkers(IC_merge,
                              ident.1 = c("IC_7d"),
                              ident.2 = c("Uninjured"),
                              logfc.threshold = 0,
                              min.pct = 0.001)

write.csv(x = IC_merge_IC_7d,
          file = "IC_merge_IC_7d.csv",
          quote = FALSE)

IC_merge_allIC <- FindMarkers(IC_merge,
                              ident.1 = c("IC_1d","IC_3d","IC_7d"),
                              ident.2 = c("Uninjured"),
                              logfc.threshold = 0,
                              min.pct = 0.001)

write.csv(x = IC_merge_allIC,
          file = "IC_merge_IC_allIC.csv",
          quote = FALSE)
```

```{r}
#Generate average values (to create background list of detectable genes)

DefaultAssay(IC_merge) <- "RNA"

avgexp_IC_merge <- AverageExpression(IC_merge, assay = 'RNA', 
                                      features = rownames(IC_merge@assays$RNA$counts),
                                      group.by = c('injury.status'))


write.csv(x = avgexp_IC_merge, 
          file = "avgexp_IC_merge.csv",
          quote = FALSE)


saveRDS(IC_merge, "IC_merge.rds")
saveRDS(IC_7d_1, "IC_7d_1.rds")
saveRDS(IC_3d_1, "IC_3d_1.rds")
saveRDS(IC_1d_1, "IC_1d_1.rds")
```

