---
title: "Untitled"
author: "Manoj"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('Seurat')
library('ggplot2')
library('plyr')
library('dplyr')
library('viridis')
library('ggthemes')
library('plotly')
library('cowplot')
library('scCustomize')
```

```{r}
LMN_Final = readRDS("LMN_Final.rds")
```

```{r}
Idents(LMN_Final) <- "seurat_clusters"

DimPlot(LMN_Final, reduction = "umap", label = FALSE, pt.size = 0.1, 
        label.size = 0, group.by =  "injury.status", alpha = 0.2, split.by = "injury.status",cols = c("#EB984E","#7FB3D5"),
        order = FALSE
) + NoLegend() + NoAxes() 
ggsave("Figure_1_B.png",height = 4,width = 8,dpi = 300,units = "in")
DimPlot(LMN_Final, reduction = "umap", label = FALSE, pt.size = 0.1, 
        label.size = 0, group.by =  "injury.status", alpha = 0.2,cols = c("#EB984E","#7FB3D5"),
        order = FALSE
) + NoLegend() + NoAxes() 
ggsave("Figure_1_B_2.png",height = 4,width = 4,dpi = 300,units = "in")
```

```{r}
#pal <- viridis(n = 30, option = "H")
#pal_inverted <- rev(pal)
library(RColorBrewer)
# Define the number of colors you need
n <- 40 # Adjust based on your requirement
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
# Generate the Spectral palette
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker, dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(size = 15))
```

```{r}
#pal <- viridis(n = 30, option = "C")
#pal_inverted <- rev(pal)
library(RColorBrewer)
n <- 40 # Adjust based on your requirement
# Generate the Spectral palette
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
Idents(LMN_Final) <- "manual.clusters.2"
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker, dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(size = 15))
ggsave("Sup_Fig_1_A.png",height = 12,width = 5,dpi = 300,units = "in",bg = "white")
DimPlot_scCustom(seurat_object = LMN_Final,figure_plot = TRUE, label = T)
ggsave("Sup_Fig_1_B.png",height = 7,width = 7,dpi = 300,units = "in",bg = "white")
Idents(LMN_Final) <- "manual.clusters.1"
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker, dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  #coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(size = 15))
ggsave("Sup_Fig_1_C.png",height = 12,width = 8,dpi = 300,units = "in",bg = "white")
DimPlot_scCustom(seurat_object = LMN_Final,figure_plot = TRUE, label = T)
ggsave("Sup_Fig_1_D.png",height = 7,width = 7,dpi = 300,units = "in",bg = "white")
```

```{r}
Idents(LMN_Final) <- "manual.clusters.2"
DimPlot_scCustom(seurat_object = LMN_Final,figure_plot = TRUE, label = F) & NoLegend() 
ggsave("Sup_Fig_1_D_1_1.1.png",height = 4,width = 5,dpi = 300,units = "in",bg = "white")
```
```{r}
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
library(RColorBrewer)
n <- 40 # Adjust based on your requirement
# Generate the Spectral palette
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker, dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  #coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        axis.text = element_text(size = 15))
ggsave("Sup_Fig_1_C_1.png",height = 4,width = 16,dpi = 300,units = "in",bg = "white")
```
```{r}
Stacked_VlnPlot(LMN_Final,features = c("Crym","Etv1","Satb2", "Sim1","Plagl1","Cntnap3", "Ttc6", "Emx2os","Cyyr1","Carpt","Tlx3","Nostrin", "Lrrc36","Crh", "Nlrp12","Pard3b","Dmbx1"))
```


```{r}
#Plot_de(LMN_Final, features = c("Crym", "Sim1", "Ttc6", "Carpt", "Crh", "Pard3b"))
Idents(LMN_Final) <- "manual.clusters.2"
pal_C <- viridis(n = 10, option = "D")
FeaturePlot_scCustom(seurat_object = LMN_Final,pt.size = 0.1,split.by = "injury.status", features = c("Crym", "Sim1", "Ttc6", "Gad2", "Crh", "Pard3b","St18"), colors_use = pal_C,order = T) & NoAxes() + theme(axis.text = element_text(size = 20),text = element_text (size = 20)) 
ggsave("Sup_Fig_1_E.png",height = 18,width = 10,dpi = 300,units = "in",bg = "white")
FeaturePlot_scCustom(seurat_object = LMN_Final,pt.size = 0.1,split.by = "injury.status", features = c("Crym", "Sim1", "Ttc6", "Gad2", "Crh", "Pard3b"), colors_use = pal_inverted,order = T) & NoAxes() + theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Sup_Fig_1_F.png",height = 18,width = 10,dpi = 300,units = "in",bg = "white")
```

```{r}
#FeaturePlot_scCustom(seurat_object = CST,pt.size = 0.1, features = "Crym", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
#ggsave("Figure_S1_C_CST_Creb5s.png",height = 4,width = 10,dpi = 300,units = "in")
#FeaturePlot_scCustom(seurat_object = HYP,pt.size = 0.1, features = "Sim1", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
#ggsave("Figure_S1_C_HYP_Creb5.png",height = 2,width = 4,dpi = 300,units = "in")
#FeaturePlot_scCustom(seurat_object = RN,pt.size = 0.1, features = "Ttc6", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
#ggsave("Figure_S1_C_RN_Creb5.png",height = 2,width = 4,dpi = 300,units = "in")
#FeaturePlot_scCustom(seurat_object = DP,pt.size = 0.1, features = "Crh", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
#ggsave("Figure_S1_C_DP_Creb5.png",height = 2,width = 4,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = MED,pt.size = 0.1, features = "Pard3b", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_S1_C_MED_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
#FeaturePlot_scCustom(seurat_object = Other,pt.size = 0.1, features = "Gad2", colors_use = pal_C,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
#ggsave("Figure_S1_C_Other_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
```


```{r,tidy=TRUE}
# Subsetting for each cluster
Idents(LMN_Final) <- "manual.clusters.2"
CST <- subset(LMN_Final, idents = "CST")
HYP <- subset(LMN_Final, idents = "HYP")
RN <- subset(LMN_Final, idents = "RN")
DP <- subset(LMN_Final, idents = "DP")
MED <- subset(LMN_Final, idents = "MED")
Other <- subset(LMN_Final, idents = "Other")
```

```{r,tidy=TRUE}
pal <- viridis(n = 10, option = "D")
FeaturePlot_scCustom(seurat_object = LMN_Final,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() + theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_full_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
#Making plot for clusters seprately 
FeaturePlot_scCustom(seurat_object = CST,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_CST_Creb5s.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = HYP,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_HYP_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = RN,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_RN_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = DP,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_DP_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = MED,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_MED_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = Other,pt.size = 0.1, features = "Creb5", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_Other_Creb5.png",height = 4,width = 8,dpi = 300,units = "in")
```
```{r}
pal <- viridis(n = 10, option = "D")
FeaturePlot_scCustom(seurat_object = LMN_Final,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() + theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_full_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
#Making plot for clusters seprately 
FeaturePlot_scCustom(seurat_object = CST,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_CST_Cryms.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = HYP,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_HYP_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = RN,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_RN_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = DP,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_DP_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = MED,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_MED_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
FeaturePlot_scCustom(seurat_object = Other,pt.size = 0.1, features = "Crym", colors_use = pal,split.by = "injury.status", order = T) & NoAxes() & NoLegend()+ theme(axis.text = element_text(size = 20),text = element_text (size = 20))
ggsave("Figure_1_C_Other_Crym.png",height = 4,width = 8,dpi = 300,units = "in")
```


#Volcano plot
```{r,tidy=TRUE}
deg_data <- read.csv("LMN_ALL_InjvUninj.csv")
Volcano_filtered_data <- deg_data %>%
  filter(!grepl("Rik", X), !grepl("^Gm", X),!grepl("Grik", X))
p = ggplot(Volcano_filtered_data, aes(x=avg_log2FC, y=-log10(p_val_adj), color=ifelse(avg_log2FC > 1 & -log10(p_val_adj) > -log10(0.05), "green", ifelse(avg_log2FC < -1 & -log10(p_val_adj) > -log10(0.05), "red", "grey"))))+
  geom_point(aes(text=paste("Gene_name:", X, "<br>FC:", avg_log2FC, "<br>P-value:", -log10(p_val_adj))), alpha=0.5) +
  scale_color_identity() +
  geom_hline(yintercept=-log10(0.05), color="blue", linetype="dashed") +
  geom_vline(xintercept=0, color="black",alpha=0.7, linetype="dashed") +
  #geom_vline(xintercept=1, color="grey", linetype="dashed") +
  #geom_vline(xintercept=-1, color="grey", linetype="dashed") +
  geom_vline(xintercept=-1, color="red", linetype="dashed") +
  geom_vline(xintercept=21, color="green", linetype="dashed") +
  labs(title="", x="Average log2 Fold Change", y="Adjusted P-value (log scale)") +
  theme_few() +theme(text = element_text(size = 24)) +
  scale_x_continuous(limits=c(-3, 3), breaks=seq(-3, 3, by=1))
p
ggsave("Figure_1_Valcano_plot_1.png",height = 6, width = 6,dpi = 300,units = "in",bg = "white")
write.csv(Volcano_filtered_data,"LMN_GO.csv",row.names = F)
```

```{r,tidy=TRUE}
p_interactive=ggplotly(p)
htmlwidgets::saveWidget(p_interactive, file="VolcanoPlot_figure_1.html")
```

```{r,tidy=TRUE}
#MA Plot
# Add a new column for color based on avg_log2FC
average_expression <- rowMeans(Volcano_filtered_data[,c("pct.1", "pct.2")])
Volcano_filtered_data$color <- ifelse(Volcano_filtered_data$avg_log2FC > 1 & Volcano_filtered_data$p_val_adj < 0.05, "green",
                         ifelse(Volcano_filtered_data$avg_log2FC < -1 & Volcano_filtered_data$p_val_adj < 0.05, "red", "grey"))
num_upregulated <- sum(Volcano_filtered_data$avg_log2FC > 1 & Volcano_filtered_data$p_val_adj < 0.05)
num_downregulated <- sum(Volcano_filtered_data$avg_log2FC < -1 & Volcano_filtered_data$p_val_adj < 0.05)
# Create an MA plot
ma_plot <- ggplot(Volcano_filtered_data, aes(x=average_expression, y=avg_log2FC, color=color)) +
  geom_point(alpha=0.5) +
  scale_color_identity() +  # This will use the colors specified in the 'color' column
  geom_hline( yintercept =  0, color="black",alpha=0.7, linetype="dashed") +
  #geom_hline(yintercept = 1, color="grey", linetype="dashed") +
  #geom_hline(yintercept = -1, color="grey", linetype="dashed") +
  geom_hline(yintercept = 1, color="green", linetype="dashed") +
  geom_hline(yintercept = -1, color="red", linetype="dashed") +
  xlab(expression(bold("Average Expression"))) + ylab(expression(bold("Log2 Fold Change"))) +
  #ggtitle("MA Plot") +
  theme_few() + 
  theme(text = element_text(size = 30)) + 
  scale_y_continuous(limits=c(-7, 7), breaks=seq(-7, 7, by=1)) +
  annotate("text", x = Inf, y = Inf, label = paste("Upregulated:", num_upregulated, "\nDownregulated:", num_downregulated), vjust=1.3, hjust=1.1, size=8, color="black")
# Print the plot
print(ma_plot)
ggsave("Figure_1_MA_Plot_1.png",height = 8,width = 8,dpi = 300,units = "in",bg = "white")
```

#Histogram
```{r}
library(ggplot2)
library(cowplot)
```

```{r,tidy=TRUE}
deg_data <- Volcano_filtered_data
# Define common aesthetics with continuous fill based on avg_log2FC
common_aes <- aes(x=avg_log2FC, fill=avg_log2FC)

# Define the color scale
color_scale <- scale_fill_gradient2(low = "red", mid = "black", high = "green", 
                                    midpoint = 0, limit = c(-3, 3),
                                    breaks = c(-0.5, 0.5))

# Define common theme
common_theme <- theme_few() + theme(text = element_text(size = 20)) +
                theme(axis.text = element_text(size=20),
                      axis.title = element_text(size=20, face="bold"),
                      plot.title = element_text(size=20, hjust = 0.5))

# Adjust the size of the labels here
label_size <- 4.5  # Increase this value to make the labels larger

# Lower plot (zoomed-in version)
p1 <- ggplot(deg_data, common_aes) + 
   geom_histogram(binwidth=0.5, aes(fill = ifelse(avg_log2FC < -1 & Volcano_filtered_data$p_val_adj < 0.05, "Red", ifelse(avg_log2FC > 1 & Volcano_filtered_data$p_val_adj < 0.05, "Green", "Default"))), color="black", alpha=0.2, show.legend=FALSE) +
  scale_fill_manual(values = c("Red" = "red", "Green" = "green", "Default" = "black")) +
  geom_vline(xintercept = 0, color="black",alpha=0.2, linetype="dashed", linewidth=0.7) +
  #geom_vline(xintercept = c(-1, 1), color="grey", linetype="dashed", linewidth=0.7, alpha=0.5) +
  geom_vline(xintercept = 1, color="green", linetype="dashed", linewidth=0.7, alpha=0.5)+
  geom_vline(xintercept = -1, color="red", linetype="dashed", linewidth=0.7, alpha=0.5)+
  geom_text(stat='bin', aes(label=ifelse(..count.. >= 1, ..count.., "")), vjust=-0.8, size=label_size, binwidth=0.5, color="black", 
            label.padding = unit(0.2, "lines"), label.size = 3, label.r = unit(0.15, "lines"), label.color = NA, fill="white") +
  xlab("Log2 Fold Change") + ylab("Number of Genes") +
  scale_x_continuous(breaks=seq(-7, 7, by=1), limits=c(-7, 7)) + 
  scale_y_continuous(breaks = seq(0, 400, by = 200)) +
  coord_cartesian(ylim = c(0, 400)) + 
  common_theme

# Upper plot (for the range with fewer genes)
p2 <- ggplot(deg_data, common_aes) + 
   geom_histogram(binwidth=0.5, aes(fill = ifelse(avg_log2FC < -1 & Volcano_filtered_data$p_val_adj < 0.05, "Red", ifelse(avg_log2FC > 1 & Volcano_filtered_data$p_val_adj < 0.05, "Green", "Default"))), color="black", alpha=0.2, show.legend=FALSE) +
  scale_fill_manual(values = c("Red" = "red", "Green" = "green", "Default" = "black")) +
  geom_vline(xintercept = 0, color="black",alpha=0.2, linetype="dashed", linewidth=0.7) +
  geom_vline(xintercept = c(-1, 1), color="grey", linetype="dashed", linewidth=0.7, alpha=0.5) +
  geom_vline(xintercept = 1, color="green", linetype="dashed", linewidth=0.7, alpha=0.5)+
  geom_vline(xintercept = -1, color="red", linetype="dashed", linewidth=0.7, alpha=0.5)+
  geom_text(stat='bin', aes(label=ifelse(..count.. >= 1000, ..count.., "")), vjust=-1.5, size=label_size, binwidth=0.5, color="black",label.padding = unit(0.2, "lines"), label.size = 3, label.r = unit(0.15, "lines"), label.color = NA, fill="white") +
  coord_cartesian(ylim = c(1000, 12000)) + 
  common_theme +
  xlab("Log2 Fold Change") + ylab("Number of Genes") + 
  scale_x_continuous(breaks=seq(-7, 7, by=1), limits=c(-7, 7)) + 
  scale_y_continuous(breaks = seq(0,12000,by=3000)) +
  annotate("text", x=-1.2, y=7000, label="Downregulated", size=5, color="red", angle= 90) +
  annotate("text", x=1.2, y=7000, label="Upregulated", size=5, color="green", angle = 270) +
  annotate("text", x=0, y=12000, label="No Change", size=5, color="blue", angle = 0)

p3 <- p2 + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) 
p4 = p1 +
  theme(axis.title.y = element_blank(),axis.text.x= element_text(angle = 90)) 

# Combine the two plots with p1 at the bottom
combined_plot <- plot_grid(p3, p4, ncol=1, align='v', rel_heights = c(2/3, 1/3))
print(combined_plot)
ggsave("Figure_1_Histogram_1.png",height = 6,width = 7,dpi = 300,units = "in",bg = "white")
```

#heatmap
```{r,fig.height=4, fig.width=9,,tidy=TRUE}
# I have manually made seletec the top 20 Upregulated and 20 Downregulated genes and made a heatmap.csv file
top_50_genes = read.csv("Heatmap_manual.csv")
heatmap_plot <- ggplot(top_50_genes, aes(x = 1, y = reorder(top_50_genes[[1]], avg_log2FC), fill = avg_log2FC)) + 
  geom_tile(color = "white") +  # Adding white border to the tiles
  geom_text(aes(label = sprintf("%.2f", avg_log2FC)), vjust = 0.5, hjust = 0.5, color = "black") +  # Removed angle for vertical orientation
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0, limits = c(-4, 4)) +
  labs(x = "", y = "", fill = "Log2FC") +
  theme_few() + theme(text = element_text(size = 14)) +
  theme(axis.text.x = element_blank(),  # Swap axis.text and axis.ticks settings
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(angle = 0, vjust = 0.5),  # Adjust angle and vjust for readability
        axis.title.y = element_text(angle = 0, vjust = 0.5)) 
heatmap_plot
ggsave("Figure_1_Heatmap_rotate.png",height = 8,width = 4,dpi = 300,units = "in",bg = "white")
```

```{r}
#horizantal heatmap
heatmap_plot <- ggplot(top_50_genes, aes(x = reorder(top_50_genes[[1]], avg_log2FC), y = 1, fill = avg_log2FC)) + 
  geom_tile(color = "white") +  # Adding white border to the tiles
  geom_text(aes(label = sprintf("%.2f", avg_log2FC)), vjust = 0.5, hjust = 0.5, color = "black", angle = 90) +
  scale_fill_gradient2(low = "red", mid = "white", high = "green", midpoint = 0, limits = c(-4, 4)) +
  labs(x = "", y = "", fill = "Log2FC") +
  theme_few() + theme(text = element_text(size = 14)) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5,hjust = 1),
        axis.title.x = element_text(angle = 90, vjust = 0.5))
print(heatmap_plot)
ggsave("Figure_1_Heatmap_.png",height = 4,width = 8,dpi = 300,units = "in",bg = "white")
```


```{r}
data=read.csv("LMN_GO.csv")
# Filter for upregulated genes: foldchange (e.g., 'avg_log2FC') >= 1 and p.adjust value (e.g., 'p_val_adj') < 0.05
upregulated_genes = data %>%
  filter(avg_log2FC >= 1, p_val_adj < 0.05)

# Filter for downregulated genes: foldchange (e.g., 'avg_log2FC') <= -1 and p.adjust value (e.g., 'p_val_adj') < 0.05
downregulated_genes = data %>%
  filter(avg_log2FC <= -1, p_val_adj < 0.05)
combined_data = bind_rows(upregulated_genes, downregulated_genes)
write.csv(combined_data,"extracted_LMN_GO.csv",row.names = F)
```

```{r}
data = read.csv("extracted_LMN_GO.csv")
upregulated = data %>% filter(avg_log2FC > 1)#, p_val_adj < 0.05)
downregulated = data %>% filter(avg_log2FC < -1)#, p_val_adj < 0.05)
```

```{r}
my.symbols = upregulated$X
Entrezid=AnnotationDbi::select(org.Mm.eg.db, keys = my.symbols,columns = c("ENTREZID", "SYMBOL"),keytype = "SYMBOL") # converting your gene name to ENTREZID
Embryo_annotation=Entrezid$ENTREZID #extrating only your entrezid for the input
genelist=sort(Embryo_annotation,decreasing = TRUE) #sorting the ID
genelist=na.omit(genelist) # removing the Null values
ego=enrichGO(gene = genelist,universe = names(Entrezid$ENTREZID),OrgDb = org.Mm.eg.db, ont = "all", readable = TRUE, minGSSize = 3, maxGSSize = 500,pvalueCutoff = 1, qvalueCutoff = 1,pAdjustMethod = "none") 
```

```{r}
edox = pairwise_termsim(ego)
write.csv(edox,"Lumbar_injury_upregulated.csv",row.names = F)
```

```{r}
# Load necessary libraries
library(dplyr)
library(readr)

# Read the CSV file
data = data.frame(ego@result)

# Split the GeneRatio column, perform the division, and add as a new column
data = data %>%
  mutate(Gene_Ratio = as.numeric(sub("(.*)/.*", "\\1", GeneRatio)) / 
         as.numeric(sub(".*/(.*)", "\\1", GeneRatio)))
data=head(data,10)
```

```{r}
library(ggplot2)
library(viridis)
library(dplyr)
library(readr)
library(stringr)
# Create the dot plot
data1 <- data %>%
  mutate(Description = str_wrap(Description, width = 40))
ggplot(data1, aes(x = Gene_Ratio, y = reorder(Description, Gene_Ratio), size = Count, color = p.adjust)) +
  geom_point(alpha = 0.7) +
  scale_color_viridis(option = "D") + # Green-themed palette from D - for green Viridis F- Red Magma  
  theme_classic() +
  theme(text = element_text(color = "black",size = 16), # Set all text color to black
        axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
        legend.title = element_text(color = "black"),
        legend.text = element_text(color = "black"),
        axis.text.x = element_text(angle = 90, vjust = 0.5),
        axis.title.x = element_text(angle = 00, vjust = 0.5),
        legend.position = "right") +
  labs(title = "",
       x = "Gene Ratio",
       y = "Pathway",
       color = "P-adjust Value",
       size = "Count") #+
  guides(
  color = guide_colourbar(title.position = "top", title.hjust = 0.5, label.theme = element_text(angle = 90))
)
ggsave("Top10Pathway.png",height = 6,width = 9, units = "in",dpi = 300)
```

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Read the data from your CSV file
data <- read.csv("Barplot.csv")

# Create the bar plot
ggplot(data, aes(x = Gene_name, y = avg_log2FC, fill = cluster)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = round(avg_log2FC, 2)), vjust = -0.5, hjust=0.5, angle = 0) +  # Add this line
  theme_linedraw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(title = "",
       x = "",
       y = "") +
  scale_fill_brewer(palette = "Paired") +
  facet_wrap(~cluster, scales = 'free_x') +
   scale_y_continuous(limits = c(NA, 12))
ggsave("Test_barplot.png",height = 6,width = 12,dpi = 300,units = "in")
```

```{r}
pbmc.markers <- FindAllMarkers(LMN_Final,split.by = "injury.status", only.pos = TRUE)
```
```{r}
pbmc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
write.csv(pbmc.markers,"Injured_vs_uninjured.csv")
```


```{r}
Idents(LMN_Final) <- "injury.status"
injured_cells <- subset(LMN_Final, idents = "injured")
Uninjured_cells <- subset(LMN_Final, idents = "uninjured")
Idents(injured_cells) <- "manual.clusters.2"
Idents(Uninjured_cells) <- "manual.clusters.2"
pbmc.markers <- FindAllMarkers(injured_cells,split.by = "injury.status",only.pos = TRUE)
write.csv(pbmc.markers,"injured_1.csv",row.names = F)
pbmc.markers <- FindAllMarkers(Uninjured_cells,split.by = "injury.status",only.pos = TRUE)
write.csv(pbmc.markers,"Uninjured_1.csv",row.names = F)
g=read.csv("Gene_name.csv")
i=read.csv("injured_1.csv")
u=read.csv("Uninjured_1.csv")
ci=merge(g,i,by="gene")
cu=merge(g,u,by="gene")
```

```{r}
write.csv(ci,"Injured_cmb.csv")
write.csv(cu,"Uninjured_cmb.csv")
```

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Read the data from your CSV file
data <- read.csv("BarPlot_forInjured_uninjued.csv")

# Create the bar plot
ggplot(data, aes(x = Gene_name, y = avg_log2FC, fill = cluster)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = round(avg_log2FC, 2)), vjust = 0.5, hjust=-0.1, angle = 90) +  # Add this line
  theme_linedraw() +
  theme(text = element_text(size = 14),
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(title = "",
       x = "",
       y = "") +
  scale_fill_brewer(palette = "Paired") +
  facet_wrap(~cluster, scales = 'free_x') +
   scale_y_continuous(limits = c(NA, 14))
ggsave("Injured_4_barplot.png",height = 10,width = 18,dpi = 300,units = "in")
```
```{r}
ggplot(data, aes(x = Gene_name, y = avg_log2FC, fill = cluster)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = round(avg_log2FC, 2)), vjust = 0.5, hjust=-0.1, angle = 90) +
  theme_linedraw() +
  theme(text = element_text(size = 14),
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
  labs(title = "",
       x = "",
       y = "") +
  scale_fill_manual(values = c("RN_Injured"="#b15928", "MED_Injured"="#ff7f00", "Other_Injured"="#6a3d9a",
                               "CST_Injured"="#1f78b4", "HYP_Injured"="#e31a1c", "DP_Injured"="#33a02c",
                               "RN_Uninjured"="#d8ac94", "MED_Uninjured"="#fdbf6f", "Other_Uninjured"="#b6a0c1",
                               "CST_Uninjured"="#a6cee3", "HYP_Uninjured"="#fb9a99", "DP_Uninjured"="#b2df8a")) +
  facet_wrap(~cluster, scales = 'free_x') +
  scale_y_continuous(limits = c(NA, 14))
ggsave("Injured_4_barplot.png",height = 10,width = 16,dpi = 300,units = "in")
```

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Assuming your data is in a dataframe called 'data' with columns 'Cluster' and 'Regulation'
# If you're reading from a CSV, you can load your data like this:
 data <- read.csv('BarPlot_Maplot.csv')

# Create the plot
ggplot(data, aes(x = Cluster, y = Regulation, fill = ifelse(Regulation > 0, 'Upregulated', 'Downregulated'))) +
  geom_bar(stat = "identity", position = "identity",alpha=0.5) +
  scale_fill_manual(values = c('Upregulated' = 'green', 'Downregulated' = 'red')) +
  theme_classic() +
   labs(y = "", x = "", title = "", fill = "") +
  geom_hline(yintercept = 0, linetype = "dashed")  +
  geom_text(aes(label = Regulation), vjust = 0.5)+ # Add values on the bars
  coord_flip() + scale_y_continuous(limits = c(-150,NA)) + # Use this if you want to flip the axes
  theme(text = element_text(size = 16,color = "black"))  # Apply global text size
ggsave("barplot_feature_1.png",units = "in",width = 6,height = 5,dpi = 300)
```

```{r}
library(RColorBrewer)
n <- 40 # Adjust based on your requirement
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
Idents(LMN_Final) <- "manual.clusters.2"
#Idents(LMN_Final) <- "injury.status"
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker,dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(size = 15))
#ggsave("Sup_Fig_1_A.png",height = 12,width = 5,dpi = 300,units = "in",bg = "white")
```

```{r}
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
library(RColorBrewer)
n <- 40 # Adjust based on your requirement
# Generate the Spectral palette
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
DotPlot_scCustom (LMN_Final,features = LMN_Final_DotPlot2$Marker, dot.scale = 6, dot.min = .01,colors_use = pal_inverted) +
  #coord_flip() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5),
        axis.text = element_text(size = 20))
ggsave("Sup_Fig_1_C_1.png",height =4,width = 17,dpi = 300,units = "in",bg = "white")
```
```{r}
LMN_Final_DotPlot2=read.csv("2_Input_Lists/LMN_Final_Dotplot2.csv")
Idents(LMN_Final) <- "manual.clusters.1"
top_markers <- LMN_Final_DotPlot2$Marker
library(RColorBrewer)
n <- 10 # Adjust based on your requirement
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
plot_list =Clustered_DotPlot(LMN_Final,features = top_markers, colors_use_exp = pal_inverted, k=6,exp_color_max = 2,exp_color_min = -1,exp_color_middle = 0,split.by = "injury.status",show_parent_dend_line = F,cluster_feature = F,cluster_ident = F,x_lab_rotate = 90,color_seed = 1,row_label_size = 12,column_label_size = 12,flip = T)
plot_list [[2]]
png("cluster_dotplot_1.png",height =6,width = 14,res = 300,units ="in",bg = "white")
plot_list[[2]]
dev.off()
```

```{r}
n <- 11 # This is the max for 'Spectral', adjust if using a different palette or need different resolution
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)

# Ensure your data and parameters are set correctly
exp_color_max <- 2
exp_color_min <- -1
exp_color_middle <- 0
Clustered_DotPlot(LMN_Final, features = top_markers, colors_use_exp = pal_inverted, k = 6,
                  exp_color_max = exp_color_max, exp_color_min = exp_color_min, ggplot_default_colors=pal_inverted,colors_use_idents = pal_inverted,
                  exp_color_middle = exp_color_middle, split.by = "injury.status",
                  show_parent_dend_line = FALSE, cluster_feature = FALSE, 
                  cluster_ident = FALSE, x_lab_rotate = 90, color_seed = 1)
ggsave("Dotplot_cluster.png",height =17,width = 5,dpi = 300,units = "in",bg = "white")
```

```{r}
library(ggplot2)
library(dplyr)

# Read the data
data <- read.csv("BarPlot_forInjured_uninjued.csv")

# Separate 'injured' and 'uninjured' from the cluster name and create a new factor 'Condition'
data <- data %>%
  mutate(Condition = ifelse(grepl("Injured", cluster), "Injured", "Uninjured"),
         Cluster = gsub("_(Injured|Uninjured)", "", cluster)) %>%
  droplevels() # Update the levels of all factors

# Create the box plot
ggplot(data, aes(x = Cluster, y = avg_log2FC, fill = Condition)) + 
  geom_boxplot(outlier.shape = NA) + # Hide outliers for cleaner plot
  geom_jitter(width = 0.2, alpha = 0.5) + # Add jittered points to show individual data points
  scale_fill_manual(values = c("Injured"="#8B0000", "Uninjured"="#FFC0CB")) + # Adjust colors as needed
  theme_linedraw() +
  theme(text = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(title = "Comparison of Injured vs Uninjured per Cluster",
       x = "Cluster",
       y = "Average Log2 Fold Change") +
  facet_wrap(~Cluster, scales = 'free')
```

```{r}
ggplot(data, aes(x = Gene_name, y = avg_log2FC, fill = cluster)) + 
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = round(avg_log2FC, 2)), vjust = 0.5, hjust=-0.1, angle = 90) +
  theme_linedraw() +
  theme(text = element_text(size = 14),
    axis.text.x = element_text(angle = 90, hjust = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
  labs(title = "",
       x = "",
       y = "") +
  scale_fill_manual(values = c("RN_Injured"="#b15928", "MED_Injured"="#ff7f00", "Other_Injured"="#6a3d9a",
                               "CST_Injured"="#1f78b4", "HYP_Injured"="#e31a1c", "DP_Injured"="#33a02c",
                               "RN_Uninjured"="#d8ac94", "MED_Uninjured"="#fdbf6f", "Other_Uninjured"="#b6a0c1",
                               "CST_Uninjured"="#a6cee3", "HYP_Uninjured"="#fb9a99", "DP_Uninjured"="#b2df8a")) +
  facet_wrap(~cluster, scales = 'free_x') +
  scale_y_continuous(limits = c(NA, 14))
#ggsave("Injured_4_barplot.png",height = 10,width = 16,dpi = 300,units = "in")
```

```{r}
# Define custom colors based on cluster and injury status
custom_colors <- c("RN_Injured"="#b15928", "MED_Injured"="#ff7f00", "Other_Injured"="#6a3d9a",
                   "CST_Injured"="#1f78b4", "HYP_Injured"="#e31a1c", "DP_Injured"="#33a02c",
                   "RN_Uninjured"="#d8ac94", "MED_Uninjured"="#fdbf6f", "Other_Uninjured"="#b6a0c1",
                   "CST_Uninjured"="#a6cee3", "HYP_Uninjured"="#fb9a99", "DP_Uninjured"="#b2df8a")

# Create a combined factor for mapping colors to each unique combination of cluster and condition
data$ClusterCondition <- with(data, paste(Cluster, Condition, sep = "_"))

# Create the box plot with fixed scales and custom colors
ggplot(data, aes(x = Condition, y = avg_log2FC, fill = ClusterCondition)) + 
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.7,) +# Add the boxplot
  scale_fill_manual(values = custom_colors) + # Use custom colors
  theme_linedraw() +
  theme(text = element_text(size = 24),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 0.5),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom") +
  labs(title = "",
       x = "",
       y = "") +
  facet_wrap(~Cluster, scales = 'free_x') + # Use fixed scales
   scale_y_continuous(limits = c(NA, 12.5))  # Use fixed scales
ggsave("Injured_4_Boxplot.png",height = 10,width = 14,dpi = 300,units = "in")
```


Manual_dotPlot
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

# Read the datasets
injured <- read.csv('Dot_plot/Injured.csv')
uninjured <- read.csv('Dot_plot/Uninjured.csv')

# Combine the two dataframes
combined <- rbind(injured, uninjured)
library(RColorBrewer)
# Define the number of colors you need
n <- 40 # Adjust based on your requirement
# Generate the Spectral palette
pal <- brewer.pal(n, "Spectral")
pal_inverted <- rev(pal)
# Create the dot plot
ggplot(combined, aes(x = Cluster, y = reorder(gene, avg_log2FC), size = pct, color = avg_log2FC)) +
  geom_point(alpha = 0.7) + 
  scale_color_gradientn(colors = pal_inverted, limits = c(-1, max(combined$avg_log2FC, 2)), oob = scales::squish) +
  scale_size(range = c(3, 10)) +
  theme_base() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.title = element_text(size = 8), # Adjust size of legend title
        legend.text = element_text(size = 6), # Adjust size of legend text
        legend.key.size = unit(1.5, 'lines'), # Adjust the size of the legend keys
        legend.key.height = unit(0.5, 'inches'), # Longer legend keys
        legend.key.width = unit(0.25, 'inches')) + # Smaller width of legend keys
  labs(title = '', x = '', y = '', color = 'Average Expression', size = 'Percentage Expressed') +
  guides(color = guide_colorbar(barwidth = 7, barheight = 1.5), size = guide_legend(override.aes = list(alpha = 1)))
``` 
```{r}
Volcano_filtered_data= read.csv("LMN_GO.csv")
average_expression <- rowMeans(Volcano_filtered_data[,c("pct.1", "pct.2")])
Volcano_filtered_data$color <- ifelse(Volcano_filtered_data$avg_log2FC > 0.5 & Volcano_filtered_data$p_val_adj < 0.05, "green",
                         ifelse(Volcano_filtered_data$avg_log2FC < -0.5 & Volcano_filtered_data$p_val_adj < 0.05, "red", "grey"))
num_upregulated <- sum(Volcano_filtered_data$avg_log2FC > 0.5 & Volcano_filtered_data$p_val_adj < 0.05)
num_downregulated <- sum(Volcano_filtered_data$avg_log2FC < -0.5 & Volcano_filtered_data$p_val_adj < 0.05)
```

